# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\tune\main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\tune\main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\tune\main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 583)
        MainWindow.setMaximumSize(QtCore.QSize(650, 583))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_6)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 631, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget_4 = QtWidgets.QWidget(self.tab)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 631, 511))
        self.widget_4.setObjectName("widget_4")
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setGeometry(QtCore.QRect(0, 0, 631, 511))
        self.widget_7.setObjectName("widget_7")
        self.most_popular_list = QtWidgets.QListWidget(self.widget_7)
        self.most_popular_list.setGeometry(QtCore.QRect(10, 10, 331, 481))
        self.most_popular_list.setObjectName("most_popular_list")
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setGeometry(QtCore.QRect(350, 10, 271, 481))
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 12, 1, 1, 1)
        self.Web_site = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Web_site.setFont(font)
        self.Web_site.setText("")
        self.Web_site.setObjectName("Web_site")
        self.gridLayout_5.addWidget(self.Web_site, 10, 1, 1, 1)
        self.discord_label = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.discord_label.setFont(font)
        self.discord_label.setText("")
        self.discord_label.setObjectName("discord_label")
        self.gridLayout_5.addWidget(self.discord_label, 11, 1, 1, 1)
        self.name_label = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.name_label.setFont(font)
        self.name_label.setTextFormat(QtCore.Qt.RichText)
        self.name_label.setWordWrap(True)
        self.name_label.setObjectName("name_label")
        self.gridLayout_5.addWidget(self.name_label, 7, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_8)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.install_masternode_button_mp = QtWidgets.QPushButton(self.widget)
        self.install_masternode_button_mp.setObjectName("install_masternode_button_mp")
        self.gridLayout_3.addWidget(self.install_masternode_button_mp, 1, 0, 2, 2)
        self.create_sh_button_mp = QtWidgets.QPushButton(self.widget)
        self.create_sh_button_mp.setAutoDefault(False)
        self.create_sh_button_mp.setDefault(False)
        self.create_sh_button_mp.setFlat(False)
        self.create_sh_button_mp.setObjectName("create_sh_button_mp")
        self.gridLayout_3.addWidget(self.create_sh_button_mp, 0, 0, 1, 2)
        self.gridLayout_5.addWidget(self.widget, 15, 1, 1, 1)
        self.add_date_label = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_date_label.setFont(font)
        self.add_date_label.setText("")
        self.add_date_label.setObjectName("add_date_label")
        self.gridLayout_5.addWidget(self.add_date_label, 13, 1, 1, 1)
        self.img_label_mp = QtWidgets.QLabel(self.widget_8)
        self.img_label_mp.setObjectName("img_label_mp")
        self.gridLayout_5.addWidget(self.img_label_mp, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget_5 = QtWidgets.QWidget(self.tab_2)
        self.widget_5.setGeometry(QtCore.QRect(0, 0, 731, 511))
        self.widget_5.setObjectName("widget_5")
        self.widget_12 = QtWidgets.QWidget(self.widget_5)
        self.widget_12.setGeometry(QtCore.QRect(0, 0, 721, 501))
        self.widget_12.setObjectName("widget_12")
        self.all_coins_list = QtWidgets.QListWidget(self.widget_12)
        self.all_coins_list.setGeometry(QtCore.QRect(10, 10, 331, 481))
        self.all_coins_list.setObjectName("all_coins_list")
        self.widget_13 = QtWidgets.QWidget(self.widget_12)
        self.widget_13.setGeometry(QtCore.QRect(350, 10, 271, 481))
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_2 = QtWidgets.QWidget(self.widget_13)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.install_masternode_ac = QtWidgets.QPushButton(self.widget_2)
        self.install_masternode_ac.setObjectName("install_masternode_ac")
        self.gridLayout_4.addWidget(self.install_masternode_ac, 1, 0, 2, 2)
        self.create_sh_button_ac = QtWidgets.QPushButton(self.widget_2)
        self.create_sh_button_ac.setAutoDefault(False)
        self.create_sh_button_ac.setDefault(False)
        self.create_sh_button_ac.setFlat(False)
        self.create_sh_button_ac.setObjectName("create_sh_button_ac")
        self.gridLayout_4.addWidget(self.create_sh_button_ac, 0, 0, 1, 2)
        self.gridLayout_7.addWidget(self.widget_2, 14, 0, 1, 3)
        self.label_16 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 13, 0, 1, 1)
        self.img_label_ac = QtWidgets.QLabel(self.widget_13)
        self.img_label_ac.setObjectName("img_label_ac")
        self.gridLayout_7.addWidget(self.img_label_ac, 0, 0, 3, 3)
        self.name_label_ac = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.name_label_ac.setFont(font)
        self.name_label_ac.setTextFormat(QtCore.Qt.RichText)
        self.name_label_ac.setWordWrap(True)
        self.name_label_ac.setObjectName("name_label_ac")
        self.gridLayout_7.addWidget(self.name_label_ac, 4, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 6, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 7, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 9, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget_9 = QtWidgets.QWidget(self.tab_3)
        self.widget_9.setGeometry(QtCore.QRect(0, 0, 621, 491))
        self.widget_9.setObjectName("widget_9")
        self.added_by_user_list = QtWidgets.QListWidget(self.widget_9)
        self.added_by_user_list.setGeometry(QtCore.QRect(10, 10, 341, 431))
        self.added_by_user_list.setObjectName("added_by_user_list")
        self.widget_15 = QtWidgets.QWidget(self.widget_9)
        self.widget_15.setGeometry(QtCore.QRect(360, 10, 261, 481))
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.create_sh_button_abu = QtWidgets.QPushButton(self.widget_15)
        self.create_sh_button_abu.setAutoDefault(False)
        self.create_sh_button_abu.setDefault(False)
        self.create_sh_button_abu.setFlat(False)
        self.create_sh_button_abu.setObjectName("create_sh_button_abu")
        self.gridLayout_8.addWidget(self.create_sh_button_abu, 4, 1, 1, 1)
        self.coin_name_abu = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setItalic(False)
        self.coin_name_abu.setFont(font)
        self.coin_name_abu.setTextFormat(QtCore.Qt.RichText)
        self.coin_name_abu.setWordWrap(True)
        self.coin_name_abu.setObjectName("coin_name_abu")
        self.gridLayout_8.addWidget(self.coin_name_abu, 0, 1, 3, 1)
        self.install_masternode_button_abu = QtWidgets.QPushButton(self.widget_15)
        self.install_masternode_button_abu.setObjectName("install_masternode_button_abu")
        self.gridLayout_8.addWidget(self.install_masternode_button_abu, 5, 1, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.widget_9)
        self.widget_14.setGeometry(QtCore.QRect(10, 450, 341, 41))
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_14)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_coin_button = QtWidgets.QPushButton(self.widget_14)
        self.add_coin_button.setObjectName("add_coin_button")
        self.gridLayout_2.addWidget(self.add_coin_button, 0, 0, 1, 1)
        self.delete_coin_button = QtWidgets.QPushButton(self.widget_14)
        self.delete_coin_button.setObjectName("delete_coin_button")
        self.gridLayout_2.addWidget(self.delete_coin_button, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget_3 = QtWidgets.QWidget(self.tab_4)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 621, 491))
        self.widget_3.setObjectName("widget_3")
        self.widget_10 = QtWidgets.QWidget(self.widget_3)
        self.widget_10.setGeometry(QtCore.QRect(0, 0, 331, 451))
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.servers_list = QtWidgets.QListWidget(self.widget_10)
        self.servers_list.setObjectName("servers_list")
        self.verticalLayout.addWidget(self.servers_list)
        self.widget_16 = QtWidgets.QWidget(self.widget_3)
        self.widget_16.setGeometry(QtCore.QRect(0, 446, 331, 41))
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_server_button = QtWidgets.QPushButton(self.widget_16)
        self.add_server_button.setObjectName("add_server_button")
        self.horizontalLayout_2.addWidget(self.add_server_button)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_16)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.widget_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.most_popular_list.setCurrentRow(-1)
        self.all_coins_list.setCurrentRow(-1)
        self.added_by_user_list.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyNode 0.1.0 ALPHA"))
        self.name_label.setText(_translate("MainWindow", "Choice coin"))
        self.install_masternode_button_mp.setText(_translate("MainWindow", "Install masternode"))
        self.create_sh_button_mp.setText(_translate("MainWindow", "Create .sh file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Most popular coins"))
        self.install_masternode_ac.setText(_translate("MainWindow", "Install masternode"))
        self.create_sh_button_ac.setText(_translate("MainWindow", "Create .sh file"))
        self.name_label_ac.setText(_translate("MainWindow", "Choice coin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "All coins"))
        self.create_sh_button_abu.setText(_translate("MainWindow", "Create .sh file"))
        self.coin_name_abu.setText(_translate("MainWindow", "Choice coin"))
        self.install_masternode_button_abu.setText(_translate("MainWindow", "Install masternode"))
        self.add_coin_button.setText(_translate("MainWindow", "Add coin"))
        self.delete_coin_button.setText(_translate("MainWindow", "Delete coin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Added by user coins"))
        self.add_server_button.setText(_translate("MainWindow", "Add server"))
        self.pushButton_2.setText(_translate("MainWindow", "Delete server"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Servers"))


class UI_addcoin_dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(408, 244)
        Dialog.setMinimumSize(QtCore.QSize(408, 244))
        Dialog.setMaximumSize(QtCore.QSize(408, 244))
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 391, 223))
        self.widget.setMaximumSize(QtCore.QSize(391, 223))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.coin_name_line = QtWidgets.QLineEdit(self.widget)
        self.coin_name_line.setObjectName("coin_name_line")
        self.gridLayout.addWidget(self.coin_name_line, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.config_file_line = QtWidgets.QLineEdit(self.widget)
        self.config_file_line.setObjectName("config_file_line")
        self.gridLayout.addWidget(self.config_file_line, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.config_folder_line = QtWidgets.QLineEdit(self.widget)
        self.config_folder_line.setObjectName("config_folder_line")
        self.gridLayout.addWidget(self.config_folder_line, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.coin_daemon_line = QtWidgets.QLineEdit(self.widget)
        self.coin_daemon_line.setObjectName("coin_daemon_line")
        self.gridLayout.addWidget(self.coin_daemon_line, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.coin_cli_name = QtWidgets.QLineEdit(self.widget)
        self.coin_cli_name.setObjectName("coin_cli_name")
        self.gridLayout.addWidget(self.coin_cli_name, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.coin_github_line = QtWidgets.QLineEdit(self.widget)
        self.coin_github_line.setObjectName("coin_github_line")
        self.gridLayout.addWidget(self.coin_github_line, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 6, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setMaximumSize(QtCore.QSize(373, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 7, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add coin"))
        self.label.setText(_translate("Dialog", "Coin Name"))
        self.label_2.setText(_translate("Dialog", "Config file"))
        self.label_3.setText(_translate("Dialog", "Config foder"))
        self.label_4.setText(_translate("Dialog", "Coin daemon"))
        self.label_5.setText(_translate("Dialog", "Coin cli"))
        self.label_6.setText(_translate("Dialog", "Coin github (git URL)"))
        self.label_7.setText(_translate("Dialog", "Coin port"))

class Install_masternode_dialog(object):
    def setupUi(self, Install_masternode_dialog):
        Install_masternode_dialog.setObjectName("Install_masternode_dialog")
        Install_masternode_dialog.resize(668, 292)
        self.tabWidget = QtWidgets.QTabWidget(Install_masternode_dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 671, 291))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(0, 0, 661, 261))
        self.widget.setObjectName("widget")
        self.log_t1 = QtWidgets.QPlainTextEdit(self.widget)
        self.log_t1.setGeometry(QtCore.QRect(220, 10, 431, 211))
        self.log_t1.setObjectName("log_t1")
        self.server_list = QtWidgets.QListWidget(self.widget)
        self.server_list.setGeometry(QtCore.QRect(9, 9, 201, 211))
        self.server_list.setObjectName("server_list")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 210, 221, 61))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cancel_button_t1 = QtWidgets.QPushButton(self.widget_2)
        self.cancel_button_t1.setObjectName("cancel_button_t1")
        self.gridLayout.addWidget(self.cancel_button_t1, 1, 0, 1, 1)
        self.install_button_t1 = QtWidgets.QPushButton(self.widget_2)
        self.install_button_t1.setObjectName("install_button_t1")
        self.gridLayout.addWidget(self.install_button_t1, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget_3 = QtWidgets.QWidget(self.tab_2)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 661, 261))
        self.widget_3.setObjectName("widget_3")
        self.log_t2 = QtWidgets.QPlainTextEdit(self.widget_3)
        self.log_t2.setGeometry(QtCore.QRect(240, 10, 411, 211))
        self.log_t2.setObjectName("log_t2")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(0, 210, 221, 61))
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cancel_button_t2 = QtWidgets.QPushButton(self.widget_4)
        self.cancel_button_t2.setDefault(True)
        self.cancel_button_t2.setObjectName("cancel_button_t2")
        self.gridLayout_2.addWidget(self.cancel_button_t2, 1, 0, 1, 1)
        self.install_button_t2 = QtWidgets.QPushButton(self.widget_4)
        self.install_button_t2.setObjectName("install_button_t2")
        self.gridLayout_2.addWidget(self.install_button_t2, 1, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setGeometry(QtCore.QRect(0, -10, 221, 241))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.port_line = QtWidgets.QLineEdit(self.widget_5)
        self.port_line.setText("")
        self.port_line.setObjectName("port_line")
        self.gridLayout_3.addWidget(self.port_line, 7, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 7, 0, 1, 1)
        self.ip_line = QtWidgets.QLineEdit(self.widget_5)
        self.ip_line.setText("")
        self.ip_line.setObjectName("ip_line")
        self.gridLayout_3.addWidget(self.ip_line, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.username_line = QtWidgets.QLineEdit(self.widget_5)
        self.username_line.setText("")
        self.username_line.setObjectName("username_line")
        self.gridLayout_3.addWidget(self.username_line, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.password_line = QtWidgets.QLineEdit(self.widget_5)
        self.password_line.setText("")
        self.password_line.setObjectName("password_line")
        self.gridLayout_3.addWidget(self.password_line, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Install_masternode_dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Install_masternode_dialog)

    def retranslateUi(self, Install_masternode_dialog):
        _translate = QtCore.QCoreApplication.translate
        Install_masternode_dialog.setWindowTitle(_translate("Install_masternode_dialog", "Dialog"))
        self.cancel_button_t1.setText(_translate("Install_masternode_dialog", "Install"))
        self.install_button_t1.setText(_translate("Install_masternode_dialog", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Install_masternode_dialog", "Server from list"))
        self.cancel_button_t2.setText(_translate("Install_masternode_dialog", "Install"))
        self.install_button_t2.setText(_translate("Install_masternode_dialog", "Cancel"))
        self.label_4.setText(_translate("Install_masternode_dialog", "Port\n"
"(default = 22)"))
        self.label_3.setText(_translate("Install_masternode_dialog", "Password"))
        self.label_2.setText(_translate("Install_masternode_dialog", "Username"))
        self.label.setText(_translate("Install_masternode_dialog", "Server IP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Install_masternode_dialog", "Other server"))


        
class Ui_Add_server_dialog(object):
    def setupUi(self, Add_server_dialog):
        Add_server_dialog.setObjectName("Add_server_dialog")
        Add_server_dialog.resize(317, 250)
        Add_server_dialog.setMaximumSize(QtCore.QSize(317, 16777215))
        self.widget_3 = QtWidgets.QWidget(Add_server_dialog)
        self.widget_3.setGeometry(QtCore.QRect(10, 10, 301, 231))
        self.widget_3.setMaximumSize(QtCore.QSize(301, 231))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(self.widget_3)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.gridLayout.addWidget(self.buttonBox_2, 8, 1, 1, 1)
        self.password_line = QtWidgets.QLineEdit(self.widget_3)
        self.password_line.setText("")
        self.password_line.setObjectName("password_line")
        self.gridLayout.addWidget(self.password_line, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.username_line = QtWidgets.QLineEdit(self.widget_3)
        self.username_line.setText("")
        self.username_line.setObjectName("username_line")
        self.gridLayout.addWidget(self.username_line, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.port_line = QtWidgets.QLineEdit(self.widget_3)
        self.port_line.setText("")
        self.port_line.setObjectName("port_line")
        self.gridLayout.addWidget(self.port_line, 7, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.ip_line = QtWidgets.QLineEdit(self.widget_3)
        self.ip_line.setText("")
        self.ip_line.setObjectName("ip_line")
        self.gridLayout.addWidget(self.ip_line, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Add_server_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(340, 200, 299, 23))
        self.buttonBox.setAccessibleDescription("")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Add_server_dialog)
        QtCore.QMetaObject.connectSlotsByName(Add_server_dialog)

    def retranslateUi(self, Add_server_dialog):
        _translate = QtCore.QCoreApplication.translate
        Add_server_dialog.setWindowTitle(_translate("Add_server_dialog", "Add server"))
        self.label.setText(_translate("Add_server_dialog", "Server IP"))
        self.label_3.setText(_translate("Add_server_dialog", "Password"))
        self.label_2.setText(_translate("Add_server_dialog", "Username"))
        self.label_4.setText(_translate("Add_server_dialog", "Port\n"
"(default = 22)"))

class Ui_server_command(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(584, 260)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 581, 251))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.server_answer = QtWidgets.QPlainTextEdit(self.widget)
        self.server_answer.setObjectName("server_answer")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.server_answer)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


    